boot.o: boot.S multiboot.h x86_desc.h types.h
idt_exception_wrappers.o: idt_exception_wrappers.S \
  idt_exception_wrappers.h
idt_interrupt_wrappers.o: idt_interrupt_wrappers.S \
  idt_interrupt_wrappers.h
x86_desc.o: x86_desc.S x86_desc.h types.h
filesys.o: filesys.c filesys.h types.h lib.h
i8259.o: i8259.c i8259.h lib.h types.h
idt.o: idt.c idt.h idt_handlers.h lib.h types.h x86_desc.h \
  idt_interrupt_wrappers.h i8259.h idt_exception_wrappers.h
idt_handlers.o: idt_handlers.c idt_handlers.h lib.h types.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h rtc.h paging.h
lib.o: lib.c lib.h types.h
paging.o: paging.c paging.h lib.h types.h
rtc.o: rtc.c rtc.h lib.h types.h
syscall_handlers.o: syscall_handlers.c syscall_handlers.h idt_handlers.h \
  lib.h types.h rtc.h
tests.o: tests.c tests.h x86_desc.h types.h idt_handlers.h lib.h idt.h \
  idt_interrupt_wrappers.h i8259.h idt_exception_wrappers.h rtc.h \
  paging.h syscall_handlers.h
